lightgbm_model:
  parameters:
    objective: 'regression'
    metric: 'rmse'
    boosting_type: 'gbdt'
    num_leaves: 30
    learning_rate: 0.013125939627011885
    n_estimators: 5354
    subsample: 0.7333462628362206
    colsample_bytree: 0.7939955572331225
    reg_alpha: 0.4873825035183108
    reg_lambda: 0.2644345188454626
    cat_smooth: 17
    min_child_samples: 25
    max_depth: 4
    random_state: 149
    
  train_params:
    # early_stopping_rounds: 50
    # verbose: True

  hyperparameter_tuning:
    enable: True
    method: 'grid_search'
    n_iter: 50
    param_grid:
      num_leaves: [25,30]
      learning_rate: [0.01, 0.006]
      n_estimators: [6000, 7000]
      subsample: [0.6, 0.7]
      colsample_bytree: [0.7, 0.8]
      reg_alpha: [1, 0.8]
      reg_lambda: [1, 0.8]
      cat_smooth: [15, 17]
      min_child_samples: [10, 19]
      max_depth: [2, 6]
    scoring: 'neg_mean_squared_error'
    verbose: -1
    random_state: 149

  train:
    train_data_path: 'data/processed/Train_data_engineered.csv'
    test_data_path: 'data/processed/Test_data_engineered.csv'

  output:
    model_output_path: 'outputs/models/lightgbm_model.pkl'
    predictiom_output_path: 'outputs/predictions/lightgbm_predictions.csv'

  model_saving:
    enable: True
    directory: 'outputs/models'
    filename: 'tuned_lightgbm_model.pkl'