lightgbm_model:
  parameters:
    objective: 'regression'
    metric: 'rmse'
    boosting_type: 'gbdt'
    num_leaves: 26
    learning_rate: 0.006
    n_estimators: 6257
    subsample: 0.7
    colsample_bytree: 0.7
    reg_alpha: 0.8
    reg_lambda: 0.8
    cat_smooth: 16
    min_child_samples: 20
    max_depth: 2
    random_state: 149
    
  train_params:
    early_stopping_rounds: 50
    verbose: True

  hyperparameter_tuning:
    enable: True
    method: 'random_search'
    n_iter: 50
    param_grid:
      num_leaves: [18,31,50]
      learning_rate: [0, 0.05, 0.1, 0.2]
      n_estimators: [5000, 7000]
      subsample: [0.6, 0.7, 0.8, 0.9]
      colsample_bytree: [0.6, 0.7, 0.8, 0.9]
      reg_alpha: [0, 1.5]
      reg_lambda: [0, 0.1, 0.5, 1]
      cat_smooth: [12, 20]
      min_child_samples: [15, 30]
      max_depth: [1, 4]
    scoring: 'neg_mean_squared_error'
    random_state: 149

  train:
    train_data_path: 'data/processed/Train_data_engineered.csv'
    test_data_path: 'data/processed/Test_data_engineered.csv'

  output:
    model_output_path: 'outputs/models/lightgbm_model.pkl'
    predictiom_output_path: 'outputs/predictions/lightgbm_predictions.csv'

  model_saving:
    enable: True
    directory: 'outputs/models'
    filename: 'tuned_lightgbm_model.pkl'